// client-vuejs/src/views/User/Register.vue
<script setup>
import { computed, reactive, ref } from 'vue';
import useVuelidate from '@vuelidate/core';
import { email, helpers, minLength, required, sameAs } from '@vuelidate/validators';
import { useRouter } from 'vue-router';
import { useUserStore } from '../../stores/userStore';
import { registerUser } from '../../dataProviders/auth';
import Message from 'primevue/message';
import FormItem from '../../components/FormItem.vue';
import Loader from '../../components/Loader.vue';

const user = {
  firstName: '',
  lastName: '',
  email: '',
  password: '',
  rePassword: '',
};

const formData = reactive({ ...user });

const router = useRouter();
const userStore = useUserStore();
const isLoading = ref(false);
const data = ref({});

const rules = computed(() => ({
  firstName: {
    required: helpers.withMessage('First Name is required.', required),
    minLength: helpers.withMessage('First Name should be at least 3 characters long.', minLength(3)),
  },
  lastName: {
    required: helpers.withMessage('Last Name is required.', required),
    minLength: helpers.withMessage('Last Name should be at least 5 characters long.', minLength(5)),
  },
  email: { 
    required: helpers.withMessage('Email is required.', required), 
    email: helpers.withMessage('Invalid email provided.', email)},
  password: {
    required: helpers.withMessage('Password is required.', required),
    minLength: helpers.withMessage('Password should be at least 4 characters long.', minLength(4)),
  },
  rePassword: { 
    required: helpers.withMessage('Confirm Password is required.', required), 
    sameAs: helpers.withMessage('Passwords don\'t match.', sameAs(formData.password)) 
  },
}));

const v$ = useVuelidate(rules, formData);

async function onSubmit() {
  const isValid = await v$.value.$validate();
  // console.log(`Is form valid: ${isValid}`)
  
  if (isValid) {
    data.value = {};
    isLoading.value = true;
    data.value = await registerUser(formData);

    if (data.value.message) {
      console.log(data.value.message);
    } else {
      userStore.setProfile(data.value);
      router.push('/');
    }
    // if (userData) {
    //   userStore.setProfile(userData);
    //   router.push('/');
    // }
    isLoading.value = false;
  }
};
</script>

<template>
  <section id="register-page">
    <div class="signupSection">
      <div class="info">
        <h2>To discover and share knowledge about the environment in order to preserve and enrich life.</h2>
      </div>
      <Loader v-if="isLoading" />
      <form class="signupForm" action="" @submit.prevent="onSubmit">
        <fieldset>
          <Message 
            v-if="data.message" 
            severity="error" 
            :life="4000"
          >
            {{ data.message }}
          </Message>
          <h2>Register</h2>
          <ul class="noBullet">
            <!-- first name -->
            <li>
              <FormItem 
                :v$="v$" 
                field="firstName" 
                label="First Name" 
                required
              >
                <input
                  class="inputFields" 
                  id="first-name" 
                  v-model="formData.firstName" 
                  placeholder="Peter"
                />
              </FormItem>
            </li>

            <!-- last name -->
            <li>
              <FormItem 
                :v$="v$" 
                field="lastName" 
                label="Last Name" 
                required
              >
                <input 
                  class="inputFields" 
                  id="last-name" 
                  v-model="formData.lastName" 
                  placeholder="Petrov"
                />
              </FormItem>
            </li>

            <!-- email -->
            <li>
              <FormItem 
                :v$="v$" 
                field="email" 
                label="Email" 
                required
              >
                <input 
                  class="inputFields"
                  id="email" 
                  v-model="formData.email" 
                  placeholder="alex@gmail.com"
                />
              </FormItem>
            </li>

            <!-- password -->
            <li>
              <FormItem 
                :v$="v$" 
                field="password" 
                label="Password" 
                required
              >
                <input 
                  class="inputFields" 
                  id="password" 
                  placeholder="******"
                  v-model="formData.password" 
                  type="password" 
                  toggle-mask
                />
              </FormItem>
            </li>

            <!-- rePassword -->
            <li>
              <FormItem 
                :v$="v$" 
                field="rePassword" 
                label="Confirm Password" 
                required
              >
                <input 
                  class="inputFields"
                  id="rePassword" 
                  placeholder="******"
                  v-model="formData.rePassword" 
                  type="password"
                  toggle-mask
                />
              </FormItem>
            </li>

            <li id="center-btn">
              <button 
                type="submit" 
                id="join-btn"
              >
                Register
              </button>
            </li>

            <li id="login-link">
              Have an account?
              <RouterLink to="/login">
                Login
              </RouterLink>
            </li>
          </ul>
        </fieldset>
      </form>
    </div>
  </section>
</template>

<style scoped>
</style>

// client-angular/src/app/user/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from 'src/app/core/auth.service';
import {
  emailValidator,
  nameValidator,
  rePasswordValidatorFactory,
} from '../../shared/validators';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['../../../form-styles.css', './register.component.css'],
})
export class RegisterComponent implements OnInit {
  form: FormGroup;

  isLoading = false;

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router
  ) {
    const passwordControl = this.fb.control('', [
      Validators.required,
      Validators.minLength(4),
    ]);
    this.form = this.fb.group({
      firstName: [
        '',
        [Validators.required, Validators.minLength(3), nameValidator],
      ],
      lastName: [
        '',
        [Validators.required, Validators.minLength(5), nameValidator],
      ],
      email: ['', [Validators.required, emailValidator]],
      password: passwordControl,
      rePassword: [
        '',
        [
          Validators.required,
          Validators.minLength(5),
          rePasswordValidatorFactory(passwordControl),
        ],
      ],
    });
  }

  ngOnInit(): void {}

  submitHandler(): void {
    const data = this.form.value;
    this.isLoading = true;

    this.authService.register(data).subscribe({
      next: () => {
        this.isLoading = false;
        this.router.navigate(['/']);
      },
      error: (err) => {
        this.isLoading = false;
        console.error(err);
        alert(err.error.message);
      },
    });
  }
}

<section id="register-page">
  <div class="signupSection">
    <div class="info">
      <h2>
        To share your best outdoor photos with our community.
      </h2>
    </div>
    <form class="signupForm" [formGroup]="form" (ngSubmit)="submitHandler()">
      <fieldset>
        <h2>Register</h2>
        <ul class="noBullet">
          <!-- first name -->
          <li>
            <label for="firstName">First Name:</label>
            <input
              [class.input-error]="
                form.get('firstName').touched && !!form.get('firstName').errors
              "
              type="text"
              class="inputFields"
              id="first-name"
              name="firstName"
              placeholder="Peter"
              formControlName="firstName"
            />
            <p
              *ngIf="
                form.get('firstName').touched &&
                form.get('firstName').errors != null &&
                form.get('firstName').errors['required']
              "
              class="error"
            >
              First name is required!
            </p>
            <p
              *ngIf="
                form.get('firstName').touched &&
                form.get('firstName').errors != null &&
                form.get('firstName').errors['nameValidator']
              "
              class="error"
            >
              First name must contain only English letters!
            </p>
            <p
              *ngIf="
                form.get('firstName').touched &&
                form.get('firstName').errors != null &&
                form.get('firstName').errors['minlength']
              "
              class="error"
            >
              First name must be at least 5 characters long!
            </p>
          </li>
          <!-- last name -->
          <li>
            <label for="lastName">Last Name:</label>
            <input
              [class.input-error]="
                form.get('lastName').touched && !!form.get('lastName').errors
              "
              type="text"
              class="inputFields"
              id="last-name"
              name="lastName"
              placeholder="Petrov"
              formControlName="lastName"
            />
            <p
              *ngIf="
                form.get('lastName').touched &&
                form.get('lastName').errors != null &&
                form.get('lastName').errors['required']
              "
              class="error"
            >
              Last name is required!
            </p>
            <p
              *ngIf="
                form.get('lastName').touched &&
                form.get('lastName').errors != null &&
                form.get('lastName').errors['nameValidator']
              "
              class="error"
            >
              Last name must contain only English letters!
            </p>
            <p
              *ngIf="
                form.get('lastName').touched &&
                form.get('lastName').errors != null &&
                form.get('lastName').errors['minlength']
              "
              class="error"
            >
              Last name must be at least 5 characters long!
            </p>
          </li>
          <!-- email -->
          <li>
            <label for="email">Email:</label>
            <input
              [class.input-error]="
                form.get('email').touched && !!form.get('email').errors
              "
              type="email"
              class="inputFields"
              id="email"
              name="email"
              formControlName="email"
              placeholder="alex@gmail.com"
            />
            <p
              *ngIf="
                form.get('email').touched &&
                form.get('email').errors != null &&
                form.get('email').errors['required']
              "
              class="error"
            >
              Email is required!
            </p>
            <p
              *ngIf="
                form.get('email').touched &&
                form.get('email').errors != null &&
                form.get('email').errors['emailValidator']
              "
              class="error"
            >
              Email is not valid!
            </p>
          </li>
          <!-- password -->
          <li>
            <label for="password">Password:</label>
            <input
              [class.input-error]="
                form.get('password').touched && !!form.get('password').errors
              "
              type="password"
              class="inputFields"
              id="password"
              name="password"
              formControlName="password"
              placeholder="******"
            />
            <p
              *ngIf="
                form.get('password').touched &&
                form.get('password').errors != null &&
                form.get('password').errors['required']
              "
              class="error"
            >
              Password is required!
            </p>
            <p
              *ngIf="
                form.get('password').touched &&
                form.get('password').errors != null &&
                form.get('password').errors['minlength']
              "
              class="error"
            >
              Password must be at least 4 characters long!
            </p>
          </li>
          <!-- repassword -->
          <li>
            <label for="repeat-password">Repeat-Password:</label>
            <input
              [class.input-error]="
                form.get('rePassword').touched &&
                !!form.get('rePassword').errors
              "
              type="password"
              class="inputFields"
              id="repeat-password"
              name="rePassword"
              formControlName="rePassword"
              placeholder="******"
            />
            <p
              *ngIf="
                form.get('rePassword').touched &&
                form.get('rePassword').errors != null &&
                form.get('rePassword').errors['required']
              "
              class="error"
            >
              Repeat Password is required!
            </p>
            <p
              *ngIf="
                form.get('rePassword').touched &&
                form.get('rePassword').errors != null &&
                form.get('rePassword').errors['rePasswordValidator']
              "
              class="error"
            >
              Passwords don't match!
            </p>
          </li>
          <li id="center-btn">
            <button [disabled]="isLoading || form.invalid" id="join-btn">
              Register
            </button>
          </li>
          <li id="login-link">
            Have an account?
            <a routerLink="/user/login">Log In</a>
          </li>
        </ul>
      </fieldset>
    </form>
  </div>
</section>
