// client/src/app/post/edit/edit.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { PostService } from '../post.service';
import { imageValidator } from '../../shared/validators';
import { IPost } from '../../shared/interfaces';

@Component({
  selector: 'app-edit',
  templateUrl: './edit.component.html',
  styleUrls: ['./edit.component.css']
})
export class EditComponent {
  post: IPost = null;
  form: FormGroup;
  isLoading = false;

  constructor(
    private fb: FormBuilder,
    private postService: PostService,
    private router: Router,
    private activatedRoute: ActivatedRoute,
  ) {
    const passwordControl = this.fb.control('', [Validators.required, Validators.minLength(4)]);
    this.form = this.fb.group({
      title: ['', [Validators.required, Validators.minLength(6)]],
      keyword: ['', [Validators.required, Validators.minLength(4)]],
      location: ['', [Validators.required, Validators.maxLength(15)]],
      date: ['', [Validators.required, Validators.minLength(10), Validators.maxLength(10)]],
      imageUrl: ['', [Validators.required, imageValidator]],
      description: ['', [Validators.required, Validators.minLength(8)]]
    });
  }

  ngOnInit(): void {
    const id = this.activatedRoute.snapshot.params['id'];
    this.postService.loadPost(id).subscribe(post => {
      this.post = post;
    });
  }

  submitHandler(): void {}
}

<section id="edit-page">
  <div class="editSection">
    <div class="info">
      <h2>Edit your own post!</h2>
    </div>
    <form [formGroup]="form" (ngSubmit)="submitHandler()" class="editForm">
      <fieldset>
        <h2>Edit Post</h2>
        <ul class="noBullet">
          <li>
            <label for="title">Title:</label>
            <input [class.input-error]="form.get('title').touched && !!form.get('title').errors" type="text"
              class="inputFields" id="title" placeholder="Beautiful sunset" name="title" formControlName="title"
              [(ngModel)]="post.title" />
            <p *ngIf="form.get('title').touched && form.get('title').errors != null && form.get('title').errors['required']"
              class="error">
              Title name is required!
            </p>
            <p *ngIf="form.get('title').touched && form.get('title').errors != null && form.get('title').errors['minlength']"
              class="error">
              Title name must be at least 6 characters long!
            </p>
          </li>
          <li>
            <label for="key-word">Keyword:</label>
            <input [class.input-error]="form.get('keyword').touched && !!form.get('keyword').errors" type="text"
              class="inputFields" id="keyword" placeholder="Sunset" name="keyword" formControlName="keyword"
              [(ngModel)]="post.keyword" />
            <p *ngIf="form.get('keyword').touched && form.get('keyword').errors != null && form.get('keyword').errors['required']"
              class="error">
              Keyword is required!
            </p>
            <p *ngIf="form.get('keyword').touched && form.get('keyword').errors != null && form.get('keyword').errors['minlength']"
              class="error">
              Keyword must be at least 4 characters long!
            </p>
          </li>
          <li>
            <label for="location">Location:</label>
            <input [class.input-error]="form.get('location').touched && !!form.get('location').errors" type="text"
              class="inputFields" id="location" placeholder="Bulgaria" name="location" formControlName="location"
              [(ngModel)]="post.location" />
            <p *ngIf="form.get('location').touched && form.get('location').errors != null && form.get('location').errors['required']"
              class="error">
              Location is required!
            </p>
            <p *ngIf="form.get('location').touched && form.get('location').errors != null && form.get('location').errors['maxlength']"
              class="error">
              Location must be at most 15 characters long!
            </p>
          </li>
          <li>
            <label for="date">Date of creation:</label>
            <input [class.input-error]="form.get('date').touched && !!form.get('date').errors" type="text"
              class="inputFields" id="date" placeholder="18.07.2023" name="date" formControlName="date"
              [(ngModel)]="post.date" />
            <p *ngIf="form.get('date').touched && form.get('date').errors != null && form.get('date').errors['required']"
              class="error">
              Date is required!
            </p>
            <p *ngIf="form.get('date').touched && form.get('date').errors != null && (form.get('date').errors['minlength'] || form.get('date').errors['maxlength'])"
              class="error">
              Date must be exactly 10 characters long!
            </p>
          </li>
          <li>
            <label for="image">Wildlife image:</label>
            <input [class.input-error]="form.get('imageUrl').touched && !!form.get('imageUrl').errors" type="text"
              class="inputFields" id="image" placeholder="http:/..." name="imageUrl" formControlName="imageUrl"
              [(ngModel)]="post.imageUrl" />
            <p *ngIf="form.get('imageUrl').touched && form.get('imageUrl').errors != null && form.get('imageUrl').errors['required']"
              class="error">
              Image is required!
            </p>
            <p *ngIf="form.get('imageUrl').touched && form.get('imageUrl').errors != null && form.get('imageUrl').errors['imageValidator']"
              class="error">
              Please enter a valid image URL!
            </p>
          </li>
          <li>
            <label for="description">Description:</label>
            <textarea [class.input-error]="form.get('description').touched && !!form.get('description').errors"
              id="description" class="inputFields" name="description" placeholder="Beautiful sunset captured..."
              formControlName="description" [(ngModel)]="post.description"></textarea>
            <p *ngIf="form.get('description').touched && form.get('description').errors != null && form.get('description').errors['required']"
              class="error">
              Description is required!
            </p>
            <p *ngIf="form.get('description').touched && form.get('description').errors != null && form.get('description').errors['minlength']"
              class="error">
              Description must be at least 8 characters long!
            </p>
          </li>
          <li id="center-btn">
            <button [disabled]="isLoading || form.invalid" id="edit-btn">Edit</button>
          </li>
        </ul>
      </fieldset>
    </form>
  </div>
</section>

// client-vuejs/src/views/Post/Edit.vue
<script setup>
import { computed, reactive, onMounted, ref } from 'vue';
import useVuelidate from '@vuelidate/core';
import { helpers, minLength, maxLength, required, url } from '@vuelidate/validators';
import { useRouter, useRoute, RouterLink } from 'vue-router';
import FormItem from '../../components/FormItem.vue';
import { getPostById } from '../../dataProviders/posts';
import Loader from '../../components/Loader.vue';

const post = ref({
  _id: '',
	author: {},
	created_at: '',
	date: '',
	description: '',
	imageUrl: '',
	keyword: '',
	location: '',
	rating: 0,
	title: '',
	updatedAt: '',
	votes: []
});

const isLoading = ref(true);
const router = useRouter();
const route = useRoute();

onMounted(async () => {
	post.value = await getPostById(route.params._id);
  isLoading.value = false;
});

const rules = computed(() => ({
  title: {
    required: helpers.withMessage('Title is required.', required),
    minLength: helpers.withMessage('Title must be at least 6 characters long.', minLength(6)),
  },
  keyword: {
    required: helpers.withMessage('Keyword is required.', required),
    minLength: helpers.withMessage('Keyword must be at least 4 characters long.', minLength(4)),
  },
  location: {
    required: helpers.withMessage('Location is required.', required),
    maxLength: helpers.withMessage('Location must be at most 15 characters long.', maxLength(15))
  },
  date: {
    required: helpers.withMessage('Date is required.', required),
    minLength: helpers.withMessage('Date must be exactly 10 characters long.', minLength(10)),
    maxLength: helpers.withMessage('Date must be exactly 10 characters long.', maxLength(10)),
  },
  imageUrl: {
    required: helpers.withMessage('Image is required.', required),
    url: helpers.withMessage('Please enter a valid image URL.', url)
  },
  description: {
    required: helpers.withMessage('Description is required.', required),
    minLength: helpers.withMessage('Description must be at least 8 characters long.', minLength(8)),
  },
}));

const v$ = useVuelidate(rules, post);

async function onSubmit() {};
</script>

<template>
<section id="edit-page">
  <div class="editSection">
      <div class="info">
        <h2>Edit your own post!</h2>
      </div>
      <Loader v-if="isLoading" />
    <form class="editForm" action="" @submit.prevent="onSubmit">
      <fieldset>
        <h2>Edit Post</h2>
        <ul class="noBullet">
          <!-- title -->
          <li>
            <FormItem 
              :v$="v$" 
              field="title" 
              label="Title:" 
              required
            >
              <input 
                class="inputFields" 
                id="title" 
                v-model="post.title"
                placeholder="Beautiful sunset"
              />
            </FormItem>
          </li>

          <!-- keyword -->
          <li>
            <FormItem 
              :v$="v$" 
              field="keyword" 
              label="Keyword:" 
              required
            >
              <input 
                class="inputFields" 
                id="keyword" 
                v-model="post.keyword" 
                placeholder="Sunset"
              />
            </FormItem>
          </li>

          <!-- location -->
          <li>
            <FormItem 
              :v$="v$" 
              field="location" 
              label="Location:" 
              required
            >
              <input 
                class="inputFields" 
                id="location" 
                v-model="post.location" 
                placeholder="Bulgaria" 
              />
            </FormItem>
          </li>

          <!-- date -->
          <li>
            <FormItem 
              :v$="v$" 
              field="date" 
              label="Date of creation:" 
              required
            >
              <input 
                class="inputFields" 
                id="date" 
                placeholder="18.05.2024" 
                v-model="post.date" 
              />
            </FormItem>
          </li>

          <!-- imageUrl -->
          <li>
            <FormItem 
              :v$="v$" 
              field="imageUrl" 
              label="Wildlife image:" 
              required
            >
              <input 
                class="inputFields" 
                id="image" 
                placeholder="http:/..." 
                v-model="post.imageUrl"
              />
            </FormItem>
          </li>

          <!-- description -->
          <li>
            <FormItem 
              :v$="v$" 
              field="description" 
              label="Description:" 
              required
            >
              <textarea 
                class="inputFields" 
                id="description" 
                placeholder="Beautiful sunset captured ..." 
                v-model="post.description"
              />
            </FormItem>
          </li>

          <li id="center-btn">
            <button type="submit" id="edit-btn">
              Edit
            </button>
          </li>
          
        </ul>
      </fieldset>
    </form>
  </div>
</section>
</template>

<style scoped>
</style>
